#!/bin/sh

# PROVIDE: iocage
# REQUIRE: LOGIN cleanvar sshd zfs
# BEFORE:  securelevel
# KEYWORD: shutdown

# Add the following lines to /etc/rc.conf to enable iocage:
#
# iocage_enable="YES"
#
#

. /etc/rc.subr

name="iocage"
rcvar=iocage_enable

# read configuration and set defaults
load_rc_config "$name"
: ${iocage_enable="NO"}
: ${iocage_lang="C.UTF-8"}
: ${iocage_parallel="NO"}
: ${iocage_parallel_jobs=""}
: ${iocage_program="/usr/local/bin/iocage"}

start_cmd="iocage_start"
stop_cmd="iocage_stop"
export LANG=$iocage_lang
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin

iocage_run()
{
    # Build an argument list to preserve quoted program paths and job limits.
    if checkyesno iocage_parallel; then
        set -- "$@" --parallel
        if [ -n "$iocage_parallel_jobs" ]; then
            set -- "$@" --jobs "$iocage_parallel_jobs"
        fi
    fi
    "$iocage_program" "$@" --rc
}

iocage_start()
{
    if checkyesno ${rcvar}; then
        echo "* [I|O|C] starting jails... "
        iocage_run start
    fi
}

iocage_stop()
{
    if checkyesno ${rcvar}; then
        echo "* [I|O|C] stopping jails... "
        iocage_run stop
    fi
}

run_rc_command "$1"
